function tmkinetics = importTMKinetics(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BRETTUPSDKINETICS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  BRETTUPSDKINETICS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  brettupSDKinetics = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\Hike Work Research\Data\TMHike\brett_up_SD - Kinetics.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Mar-2020 09:30:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "LAnklePower", "LKneePower", "LHipPower", "LAnkleMomentx", "LAnkleMomenty", "LAnkleMomentz", "LKneeMomentX", "LKneeMomentY", "LKneeMomentZ", "LHipMomentx", "LHipMomenty", "LHipMomentz", "LeftZForce", "RightZforce", "VarName16"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 16, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 16, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tmkinetics = readtable(filename, opts);

end