function WalkTest6Report1 = importForcesTM(filename, dataLines)
%IMPORTFILE Import data from a text file
%  WALKTEST6REPORT1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  WALKTEST6REPORT1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  WalkTest6Report1 = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\Treadmill TMM\WalkTest_6 - Report1.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Sep-2019 15:34:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "COPx", "COPy", "ForceZ", "ForceY", "ForceX", "VarName7"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 7, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 7, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
WalkTest6Report1 = readtable(filename, opts);

end