function DBForces = importDualBelt(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DANDOWNDDFORCES = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DANDOWNDDFORCES = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  DandownDDForces = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\Hike Work Research\Data\TMHike\Dan_down_DD - Forces.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Mar-2020 11:37:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "LCOPx", "LCOPy", "LForceZ", "LForceY", "LForceX", "RForceX", "RForceY", "RForceZ", "RCOPx", "RCOPy", "VarName12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 12, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 12, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
DBForces = readtable(filename, opts);

end